# Model arguments
model_name_or_path: /leonardo_scratch/large/userexternal/lmoroni0/minestral_models/minestral-1B-100B_it-100B_en-cx-full
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
chat_template: "{% if messages[0]['role'] == 'user' or messages[0]['role'] == 'system' %}{{ bos_token }}{% endif %}{% for message in messages %}{{ '<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n' }}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% elif messages[-1]['role'] == 'assistant' %}{{ eos_token }}{% endif %}"
dataset_mixer:
  /leonardo_scratch/large/userexternal/lmoroni0/datasets_sft/ultrachat_200k: 1.0 # /leonardo_scratch/large/userexternal/lmoroni0/datasets_sft/ultrachat_200k: 1 # ENGLISH data
  # /leonardo/home/userexternal/lmoroni0/__Work/alignment-handbook/ultrafeedback-translated-ita: 1 # mii-community/ultrafeedback-translated-ita: 0.5 # ITALIAN data
  # /leonardo/home/userexternal/lmoroni0/__Work/alignment-handbook/alpaca-chat-format-v2: 1.0 # EN
dataset_splits:
- train_sft
- test_sft
preprocessing_num_workers: 12
auto_insert_empty_system_msg: true

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
# hub_model_id: example1
# hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 1
output_dir: /leonardo_scratch/large/userexternal/lmoroni0/runs_sft/minestral_final_ultrachat_debug
overwrite_output_dir: true
per_device_eval_batch_size: 16
per_device_train_batch_size: 32
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1