# Model arguments
model_name_or_path: /leonardo_scratch/large/userexternal/lmoroni0/runs_sft/minestral_30k_sft_ITA
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  # argilla/ultrafeedback-binarized-preferences-cleaned : 0.5 # ENGLISH data 
  ultrafeedback-preferences-translated-ita : 1 # ITALIAN data
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
# hub_model_id: zephyr-7b-dpo-full
learning_rate: 5.0e-7
log_level: info
report_to:
- wandb
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: /leonardo_scratch/large/userexternal/lmoroni0/runs_dpo/minestral_30k_dpo_ITA
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
# ush_to_hub: true
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1